
Mode Find the modal value
#### Description
Finds the modal value of an object (usually a factor).
Usage
Mode(x,na.rm=FALSE)
print.desc 23
#### Arguments 
x An object, usually a factor.
na.rm A dummy argument to make it compatible with calls to ‘mean’, etc.
Details
‘Mode’ finds the modal value of the object. If there are multiple modal values, it returns an appropriate
message. If ‘Mode’ is called with a continuous variable, it will not in general return a sensible
answer. It does not attempt to estimate the density of the values and return an approximate modal
value.
Value
The modal value of the object as a character string.
Note
This is not the same as ‘mode’ that determines the data mode of an object.
Author(s)
Jim Lemon
See Also
describe
print.desc Display descriptive stats output
#### Description
Displays a list of descriptive statistics produced by ‘describe’.
Usage
## S3 method for class 'desc'
print(x,ndec=2,...)
#### Arguments 
x a list of descriptive statistics produced by ‘describe’
ndec The number of decimal places to display.
... additional #### Arguments  passed to ‘print’
24 print.freq
Details
‘print.desc’ displays the list of descriptive statistics produced by the ‘describe’ function.
Value
nil
Author(s)
Jim Lemon
See Also
describe
#### Examples 
test.df<-data.frame(A=c(sample(1:10,99,TRUE),NA),C=sample(LETTERS,100,TRUE))
test.desc<-describe(test.df)
print(test.desc)
