
freq Calculate a frequency table
#### Description
Calculates one or more frequency table(s) from a vector, matrix or data frame.
Usage
freq(x,variable.labels=NULL,display.na=TRUE,decr.order=TRUE)
freq 19
#### Arguments 
x a vector, matrix or data frame.
variable.labels
optional labels for the variables. The default is the name of the variable passed
or the ‘names’ attribute if the variable has more than 1 dimension.
display.na logical - whether to display counts of NAs.
decr.order Whether to order each frequency table in decreasing order.
Details
‘freq’ calls ‘table’ to get the frequency counts and builds a list with one or more components
containing the value labels and counts.
Value
A list with one or more components. Each component includes the values of the relevant variable
as the names.
Note
The limit on the number of bins has been removed, so passing a numeric vector with many levels
may produce a huge, useless "frequency" table.
Author(s)
Jim Lemon
See Also
print.freq
#### Examples 
A<-sample(1:10,130,TRUE)
A[sample(1:130,6)]<-NA
C<-sample(LETTERS[1:14],130,TRUE)
C[sample(1:130,7)]<-NA
test.df<-data.frame(A,C)
freq(test.df)
20 htmlize
HTMLgraph Create a graphic in HTML output (R2html).
#### Description
Creates a graphic file and links it to the HTML output.
Usage
HTMLgraph(listfile, graphfile = NULL,type = "png",...)
#### Arguments 
listfile The name of the HTMLize listing file.
graphfile The name for the graphic file (see Details).
type The graphic format in which to write the image.
... Additional #### Arguments  - currently ignored.
Details
‘HTMLgraph’ sets up a graphic device to allow an R graphic to be written to a file and that file linked
to the HTML listing. If no filename is passed, a name is constructed from ‘fig’ and a number
that does not match any existing ‘fignnn...’ file. Only ‘bmp, jpeg’ and ‘png’ files are currently
handled, defaulting to the last.
Value
nil
Author(s)
Philippe Grosjean
