Package ‘pivottabler’
February 17, 2019
Type Package
Title Create Pivot Tables in R
Version 1.1.0

#### Description
 Create regular pivot tables with just a few lines of R.
More complex pivot tables can also be created, e.g. pivot tables
with irregular layouts, multiple calculations and/or derived
calculations based on multiple data frames. Pivot tables are
constructed using R only and can be written to a range of
output formats (plain text, 'HTML', 'Latex' and 'Excel'),
including with styling/formatting.
Depends R (>= 3.3.0)
Imports R6 (>= 2.2.0), dplyr (>= 0.5.0), data.table (>= 1.10.0),
jsonlite (>= 1.1), htmltools(>= 0.3.5), htmlwidgets (>= 0.8)
Suggests ggplot2 (>= 2.2.0), lubridate (>= 1.5.0), listviewer (>=
1.4.0), openxlsx (>= 4.0.17), basictabler (>= 0.2.0), shiny,
knitr, rmarkdown, testthat
License GPL-3
Encoding UTF-8
LazyData true
URL https://github.com/cbailiss/pivottabler
BugReports https://github.com/cbailiss/pivottabler/issues
VignetteBuilder knitr
RoxygenNote 6.1.1
NeedsCompilation no
Author Christopher Bailiss [aut, cre]
Maintainer Christopher Bailiss <cbailiss@gmail.com>
Repository CRAN
Date/Publication 2019-02-17 13:50:03 UTC
1R topics documented:
2
R topics documented:
bhmtraindisruption . . . . . . . .
bhmtrains . . . . . . . . . . . . .
checkArgument . . . . . . . . . .
cleanCssValue . . . . . . . . . . .
containsText . . . . . . . . . . . .
convertPvtStyleToBasicStyle . . .
convertPvtTblToBasicTbl . . . . .
exportValueAs . . . . . . . . . . .
getBlankTheme . . . . . . . . . .
getCompactTheme . . . . . . . .
getDefaultTheme . . . . . . . . .
getLargePlainTheme . . . . . . .
getNextPosition . . . . . . . . . .
getPvtStyleDeclarations . . . . . .
getSimpleColoredTheme . . . . .
getTheme . . . . . . . . . . . . .
getXlBorderFromCssBorder . . .
getXlBorderStyleFromCssBorder .
isNumericValue . . . . . . . . . .
isTextValue . . . . . . . . . . . .
parseColor . . . . . . . . . . . . .
parseCssBorder . . . . . . . . . .
parseCssSizeToPt . . . . . . . . .
parseCssSizeToPx . . . . . . . . .
parseCssString . . . . . . . . . .
parseXlBorder . . . . . . . . . . .
PivotBatch . . . . . . . . . . . . .
PivotBatchCalculator . . . . . . .
PivotBatchStatistics . . . . . . . .
PivotCalculation . . . . . . . . . .
PivotCalculationGroup . . . . . .
PivotCalculationGroups . . . . . .
PivotCalculator . . . . . . . . . .
PivotCell . . . . . . . . . . . . .
PivotCells . . . . . . . . . . . . .
PivotData . . . . . . . . . . . . .
PivotDataGroup . . . . . . . . . .
PivotFilter . . . . . . . . . . . . .
PivotFilterOverrides . . . . . . . .
PivotFilters . . . . . . . . . . . .
PivotHtmlRenderer . . . . . . . .
PivotLatexRenderer . . . . . . . .
PivotOpenXlsxRenderer . . . . .
PivotOpenXlsxStyle . . . . . . . .
PivotOpenXlsxStyles . . . . . . .
PivotStyle . . . . . . . . . . . . 































































































































































































9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
19
20
22
23
24
25
27
28
29
31
32
34
35
36
37
38
40
41bhmtraindisruption
PivotStyles . . . .
PivotTable . . . . .
pivottabler . . . . .
pivottablerOutput .
processIdentifier . .
processIdentifiers .
pvtperfresults . . .
pvtperfsummary . .
qhpvt . . . . . . .
qlpvt . . . . . . . .
qpvt . . . . . . . .
renderBasicTable .
renderPivottabler .
skipExportingValue
trainstations . . . 




.
.
.
.
Index
bhmtraindisruption
42
43
47
48
48
49
49
50
51
52
52
54
54
55
55
56
Birmingham Train Disruptions, Dec 2016-Feb 2017.

#### Description

A dataset containing details of the trains in the bhmtrains dataset that were partially/wholly can-
celled and/or reinstated.

#### Usage
<pre><code>

bhmtraindisruption
Format
A data frame with 2982 rows and 10 variables:
ServiceId Unique train identifier
LastCancellationAt Time of the last cancellation
LastCancellationLocation 3-letter code denoting the location of the last cancellation
LastCancellationReasonCategory The broad reason why the train was cancelled
LastCancellationReasonDesc A more specific reason why the train was cancelled
LastReinstatedAt Time of the last reinstatement
LastChangeOfOriginAt Time of the last change of origin
LastChangeOfOriginLocation 3-letter code denoting the location of the last change of origin
LastChangeOfOriginReasonCategory The broad reason why the origin was changed
LastChangeOfOriginReasonDesc A more specific reason why the origin was changed
Source
http://www.recenttraintimes.co.uk/4
