
percent Numeric vector with percentage representation
Description
Numeric vector with percentage representation
Usage
percent(x, digits, format = "f", ...)
## Default S3 method:
percent(x, digits = 2L, format = "f", ...)
## S3 method for class 'character'
percent(x, digits = NA, format = "f", ...)
Arguments
x a numeric vector.
digits an integer to indicate the number of digits of the percentage string.
format format type passed to formatC.
... additional parameters passed to formattable.
prefix 27
Examples
percent(rnorm(10, 0, 0.1))
percent(rnorm(10, 0, 0.1), digits = 0)
percent("0.5%")
percent(c("15.5%", "25.12%", "73.5"))
prefix Formattable object with prefix
Description
Formattable object with prefix
Usage
prefix(x, prefix = "", sep = "", ..., na.text = NULL)
Arguments
x an object
prefix a character vector put in front of each non-missing value in x as being formatted.
sep separator
... additional parameter passed to formattable.
na.text text for missing values in x.
Examples
prefix(1:10, "A")
prefix(1:10, "Choice", sep = " ")
prefix(c(1:10, NA), prefix = "A", na.text = "(missing)")
prefix(rnorm(10, 10), "*", format = "d")
prefix(percent(c(0.1,0.25)), ">")
