---
title: "``formattable::normalize``: "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(formattable)
```

digits Numeric vector showing pre-specific digits
Description
Numeric vector showing pre-specific digits
Usage
digits(x, digits, format = "f", ...)
12 formattable
Arguments
x a numeric vector
digits an integer to indicate the number of digits to show.
format format type passed to formatC.
... additional parameters passed to formattable.
Examples
digits(pi, 2)
digits(123.45678, 3)
formattable Generic function to create formattable object
Description
This function is a generic function to create formattable object, i.e. an object to which a formatting
function and related attribute are attached. The object works as ordinary object yet has specially
defined behavior as being printed or converted to a string representation.
Usage
formattable(x, ...)
Arguments
x an object.
... arguments to be passed to methods.
Value
a formattable object
formattable.data.frame 13
formattable.data.frame
Create a formattable data frame
Description
This function creates a formattable data frame by attaching column or area formatters to the data
frame. Each time the data frame is printed or converted to string representation, the formatter
function will use the formatter functions to generate formatted cells.
Usage
## S3 method for class 'data.frame'
formattable(x, ..., formatter = "format_table",
preproc = NULL, postproc = NULL)
Arguments
x a data.frame
... arguments to be passed to formatter.
formatter formatting function, format_table in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Details
The formattable data frame is a data frame with lazy-bindings of prespecified column formatters or
area formatters. The formatters will not be applied until the data frame is printed to console or in a
dynamic document. If the formatter function has no side effect, the formattable data frame will not
be changed even if the formatters are applied to produce the printed version.
Value
a formattable data.frame
See Also
format_table, area
Examples
# mtcars (mpg in red)
formattable(mtcars,
list(mpg = formatter("span", style = "color:red")))
# mtcars (mpg in red if greater than median)
formattable(mtcars, list(mpg = formatter("span",
14 formattable.Date
style = function(x) ifelse(x > median(x), "color:red", NA))))
# mtcars (mpg in red if greater than median, using formula)
formattable(mtcars, list(mpg = formatter("span",
style = x ~ ifelse(x > median(x), "color:red", NA))))
# mtcars (mpg in gradient: the higher, the redder)
formattable(mtcars, list(mpg = formatter("span",
style = x ~ style(color = rgb(x/max(x), 0, 0)))))
# mtcars (mpg background in gradient: the higher, the redder)
formattable(mtcars, list(mpg = formatter("span",
style = x ~ style(display = "block",
"border-radius" = "4px",
"padding-right" = "4px",
color = "white",
"background-color" = rgb(x/max(x), 0, 0)))))
# mtcars (mpg in red if vs == 1 and am == 1)
formattable(mtcars, list(mpg = formatter("span",
style = ~ style(color = ifelse(vs == 1 & am == 1, "red", NA)))))
# hide columns
formattable(mtcars, list(mpg = FALSE, cyl = FALSE))
# area formatting
formattable(mtcars, list(area(col = vs:carb) ~ formatter("span",
style = x ~ style(color = ifelse(x > 0, "red", NA)))))
df <- data.frame(a = rnorm(10), b = rnorm(10), c = rnorm(10))
formattable(df, list(area() ~ color_tile("transparent", "lightgray")))
formattable(df, list(area(1:5) ~ color_tile("transparent", "lightgray")))
formattable(df, list(area(1:5) ~ color_tile("transparent", "lightgray"),
area(6:10) ~ color_tile("transparent", "lightpink")))
formattable.Date Create a formattable Date vector
Description
Create a formattable Date vector
Usage
## S3 method for class 'Date'
formattable(x, ..., formatter = "format.Date",
preproc = NULL, postproc = NULL)
formattable.default 15
Arguments
x a vector of class Date.
... arguments to be passed to formatter.
formatter formatting function, format.Date in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable Date vector
Examples
dates <- as.Date("2015-04-10") + 1:5
fdates <- formattable(dates, format = "%m/%d/%Y")
fdates
fdates + 30
formattable.default Create a formattable object
Description
Create a formattable object
Usage
## Default S3 method:
formattable(x, ..., formatter, preproc = NULL,
postproc = NULL)
Arguments
x an object.
... arguments to be passed to formatter.
formatter formatting function, formatC in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable object that inherits from the original object.
Examples
formattable(rnorm(10), formatter = "formatC", digits = 1)
16 formattable.logical
formattable.factor Create a formattable factor object
Description
Create a formattable factor object
Usage
## S3 method for class 'factor'
formattable(x, ..., formatter = "vmap", preproc = NULL,
postproc = NULL)
Arguments
x a factor object.
... arguments to be passed to formatter.
formatter formatting function, vmap in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable factor object.
Examples
formattable(as.factor(c("a", "b", "b", "c")),
a = "good", b = "fair", c = "bad")
formattable.logical Create a formattable logical vector
Description
Create a formattable logical vector
Usage
## S3 method for class 'logical'
formattable(x, ..., formatter = "ifelse", preproc = NULL,
postproc = NULL)
formattable.numeric 17
Arguments
x a logical vector.
... arguments to be passed to formatter.
formatter formatting function, formattable::ifelse in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable logical vector.
Examples
logi <- c(TRUE, TRUE, FALSE)
flogi <- formattable(logi, "yes", "no")
flogi
!flogi
any(flogi)
all(flogi)
formattable.numeric Create a formattable numeric vector
Description
Create a formattable numeric vector
Usage
## S3 method for class 'numeric'
formattable(x, ..., formatter = "formatC", preproc = NULL,
postproc = NULL)
Arguments
x a numeric vector.
... arguments to be passed to formatter.
formatter formatting function, formatC in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable numeric vector.
18 formattable.POSIXct
Examples
formattable(rnorm(10), format = "f", digits = 1)
formattable(rnorm(10), format = "f",
flag="+", digits = 1)
formattable(1:10,
postproc = function(str, x) paste0(str, "px"))
formattable(1:10,
postproc = function(str, x)
paste(str, ifelse(x <= 1, "unit", "units")))
formattable.POSIXct Create a formattable POSIXct vector
Description
Create a formattable POSIXct vector
Usage
## S3 method for class 'POSIXct'
formattable(x, ..., formatter = "format.POSIXct",
preproc = NULL, postproc = NULL)
Arguments
x a vector of class POSIXct.
... arguments to be passed to formatter.
formatter formatting function, format.POSIXct in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable POSIXct vector
Examples
times <- as.POSIXct("2015-04-10 09:30:15") + 1:5
ftimes <- formattable(times, format = "%Y%m%dT%H%M%S")
ftimes
ftimes + 30
formattable.POSIXlt 19
formattable.POSIXlt Create a formattable POSIXlt vector
Description
Create a formattable POSIXlt vector
Usage
## S3 method for class 'POSIXlt'
formattable(x, ..., formatter = "format.POSIXlt",
preproc = NULL, postproc = NULL)
Arguments
x a vector of class POSIXlt.
... arguments to be passed to formatter.
formatter formatting function, format.POSIXlt in default.
preproc pre-processor function that prepares x for formatting function.
postproc post-processor function that transforms formatted output for printing.
Value
a formattable POSIXlt vector
Examples
times <- as.POSIXlt("2015-04-10 09:30:15") + 1:5
ftimes <- formattable(times, format = "%Y%m%dT%H%M%S")
ftimes
ftimes + 30
formattableOutput Widget output function for use in Shiny
Description
Widget output function for use in Shiny
Usage
formattableOutput(outputId, width = "100%", height = "0")
20 formatter
Arguments
outputId output variable to read from
width a valid CSS width or a number
height valid CSS height or a number
