Package ‘tbltools’
October 30, 2018
Title Tools for Working with Tibbles
Version 0.0.2
Description Tools for working with tibbles, or data.frame-like objects
generated by the 'tibble' package <https://tibble.tidyverse.org/>. Functions
assist in converting objects to tibbles and creating frequency tables.
License GPL-3
Encoding UTF-8
LazyData true
Imports tfse, tibble, rlang, tidyselect
Suggests testthat, covr
RoxygenNote 6.1.0.9000
URL https://github.com/mkearney/tbltools
BugReports https://github.com/mkearney/tbltools/issues
NeedsCompilation no
Author Michael W. Kearney [aut, cre] (<https://orcid.org/0000-0002-0730-4694>)
Maintainer Michael W. Kearney <kearneymw@missouri.edu>
Repository CRAN
Date/Publication 2018-10-30 16:50:03 UTC
R topics documented:
as_tbl 2
env_tbls . 2
repos_back . 3
repos_front . 4
tabsort 4
tidyselector . 5
Index 7
1
2 env_tbls
as_tbl as_tbl
Description
See tibble::as_tibble for details.
#### Usage
as_tbl(x, row_names = FALSE)
Arguments
x Data
row_names Logical indicating whether to convert non-null row names into the first column.
Examples
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## convert to tibble
as_tbl(d)
## convert to tibble and create row_names variable
as_tbl(d, row_names = TRUE)


repos_back move vars to back
Description
move vars to back
#### Usage
repos_back(data, ...)
Arguments
data data frame
... columns to move to back
Value
Reordered data frame.
Examples
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## move x to back
repos_back(d, x)


