Package ‘tbltools’
October 30, 2018
Title Tools for Working with Tibbles
Version 0.0.2
Description Tools for working with tibbles, or data.frame-like objects
generated by the 'tibble' package <https://tibble.tidyverse.org/>. Functions
assist in converting objects to tibbles and creating frequency tables.
License GPL-3
Encoding UTF-8
LazyData true
Imports tfse, tibble, rlang, tidyselect
Suggests testthat, covr
RoxygenNote 6.1.0.9000
URL https://github.com/mkearney/tbltools
BugReports https://github.com/mkearney/tbltools/issues
NeedsCompilation no
Author Michael W. Kearney [aut, cre] (<https://orcid.org/0000-0002-0730-4694>)
Maintainer Michael W. Kearney <kearneymw@missouri.edu>
Repository CRAN
Date/Publication 2018-10-30 16:50:03 UTC
R topics documented:
as_tbl 2
env_tbls . 2
repos_back . 3
repos_front . 4
tabsort 4
tidyselector . 5
Index 7
1
2 env_tbls
as_tbl as_tbl
Description
See tibble::as_tibble for details.
#### Usage
as_tbl(x, row_names = FALSE)
Arguments
x Data
row_names Logical indicating whether to convert non-null row names into the first column.
#### Examples
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## convert to tibble
as_tbl(d)
## convert to tibble and create row_names variable
as_tbl(d, row_names = TRUE)
env_tbls Convert all data frames in environment into tibbles
Description
Converts data frames found in a given environment into tibbles (tbl_df)
#### Usage
env_tbls(env = globalenv(), row_names = TRUE)
Arguments
env Name of environment from which data frames should be converted to tibbles.
Defaults to global environment.
row_names Logical indicating whether to create a row_names variable if non-auto row names
are found.

#### Value
The function will print messages when converting occurs and it will print a final completion message,
but otherwise returns nothing.
#### Examples
```{r}
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## convert data frames in global environment to tibbles
env_tbls()
```

repos_back move vars to back
Description
move vars to back
#### Usage
repos_back(data, ...)
Arguments
data data frame
... columns to move to back
Value
Reordered data frame.
#### Examples
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## move x to back
repos_back(d, x)



``repos_front`` move vars to front
Description
move vars to front
#### Usage
repos_front(data, ...)
Arguments
data data frame
... columns to move to front
Value
Reordered data frame.
#### Examples
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## move y to front
repos_front(d, y)
tabsort tabsort
Description
Returns a sorted (descending) frequency tbl
#### Usage
tabsort(.data, ..., prop = TRUE, na_omit = TRUE, sort = TRUE)
ntbl(.data, ...)
tidyselector 5
Arguments
.data Data
... Unquoted column names of variables to include in table. Default is to use all
columns.
prop Logical indicating whether to include a proportion of total obs column.
na_omit Logical indicating whether to exclude missing. If all responses are missing, a
missing value is used as the single category.
sort Logical indicating whether to sort the returned object.
Value
Frequency tbl
#### Examples
## generate example data
x <- sample(letters[1:4], 200, replace = TRUE)
y <- sample(letters[5:8], 200, replace = TRUE)
## count and sort frequencies for each vector
tabsort(x)
tabsort(y)
## combine x and y into data frame
dat <- data.frame(x, y)
## select columns and create freq table
tabsort(dat, x)
tabsort(dat, x, y)
tidyselector tidyselector
Description
Select columns using tidy eval
#### Usage
tidyselector(data, ...)
Arguments
data data frame
... vars to select
6 tidyselector
Value
Data with selected columns.
#### Examples
## data with row names
d <- data.frame(x = rnorm(5), y = rnorm(5), row.names = letters[1:5])
## select only x
tidyselector(d, x)
Index
as_tbl, 2
as_tibble, 2
env_tbls, 2
ntbl (tabsort), 4
repos_back, 3
repos_front, 4
tabsort, 4
tidyselector, 5
7
