
dyCrosshair
The dyCrosshair plugin draws a crosshair line over the point closest
to the mouse when the user hovers over the graph. It has a "direction"
option which is provided in the R wrapper function and then forwarded
to the plugin using the "options" argument to dyPlugin.

#### Description


The dyCrosshair plugin draws a crosshair line over the point closest to the mouse when the user
hovers over the graph. It has a "direction" option which is provided in the R wrapper function and
then forwarded to the plugin using the "options" argument to dyPlugin.

#### Usage
<pre><code>

dyCrosshair(dygraph, direction = c("both", "horizontal", "vertical"))

</code></pre>
#### Arguments

dygraph: Dygraph to add plugin to
direction
Crosshair direction. Valid options are: "both", "horizontal", "vertical"

#### Value

Dygraph with Crosshair plugin enabled
dyUnzoom
33

#### Examples
```{r}

library(dygraphs)
dygraph(nhtemp, main = "New Haven Temperatures") %>%
dyShading(from = "1920-1-1", to = "1930-1-1") %>%
dyShading(from = "1940-1-1", to = "1950-1-1")
dygraph(nhtemp, main = "New Haven Temperatures") %>%
dyShading(from = "48", to = "52", axis = "y") %>%
dyShading(from = "50", to = "50.1", axis = "y", color = "black")
