
auto_var_types Automatically assign var_types to the attributes
#### Description 

If the user did not provide var_types, the function will preassume every variables to be quantitative variables. If a variable's type is character but either the user or the automatic step said it's a quantitative variable, the var_types attribute for that variable will be overwritten as categorical variable. At the same time, a warning message will be printed on the screen.

#### Usage 
<pre><code>

auto_var_types(tbl)

</code></pre>
#### Arguments
* tbl The imported data.frame

``ezmarkup`` Easy way to "markup" a table before it is sent to be displayed
#### Description 

The final step of an analysis is to export the tables generated through analytical scripts to the desired platform, such as a pdf, a rmarkdown document or even a Shiny page. Sometimes, a lot of people wants to reorganize the data in a more human readable format. For example, people like to put the
standard deviation inside a pair of parentheses after the mean. People also like to put the low and high ends of confidence interval inside a pair of parenthese, separated by " ~ ", after the estimated average. However, as far as I know, so far there isn't a straight forward function to deal with this
need. This function is built to address this issue.
#### Usage 
<pre><code>

ezmarkup(tbl, pattern)

</code></pre>
#### Arguments

* ``tbl`` The input table
* ``pattern`` The grouping pattern. Each dot "." represent one column. If two or more columns need to be combined in some certain formats, they should be put together inside a pair of brackets "[ ]". You can add any special characters, such as "(" and "~", inside the pair of brackets but please don't leave those special characters outside the brackets. If you want to add a dot as a special character. Please use "^.^" for every single dot you would like to add.

#### Examples
```{r}
library(dplyr)
dt <- mtcars %>% group_by(cyl) %>% select(gear, carb) %>% ezsummary_categorical(n=TRUE)
ezmarkup(dt, "...[.(.)]")
ezmarkup(dt, "..[. (. ~ .)]")
```
