

theme_elements ggplot2 theme attribute inheritance network (directed)
#### Description
A list of two datasets, vertices and edges, containing data on the inheritance structure of theme
elements in ggplot2 (see http://docs.ggplot2.org/current/theme.html) The variables are as
follows:

#### Usage
theme_elements

#### Format
A list of two data frames:
• the edges data frame consists of two variables of length 48:
– child: Theme element that inherits its properties from the corresponding parent element
– parent: Theme element that passes its properties to its children
• the vertices data frame consists of one variable with information on 53 theme elements:
– name: Name of the theme element

theme_net Theme for network visualization
#### Description
Themes set the general aspect of the plot such as the colour of the background, gridlines, the size
and colour of fonts. theme_net provides access to the regular ggplot2 theme, but removes any
background, axes, and ensures an aspect ratio of 1 for better viewing of networks and graphs.

#### Arguments
base_size base font size
base_family base font family

#### Examples
library(ggplot2)
data(blood)
p <- ggplot(data = blood$edges, aes(from_id = from, to_id = to))
p + geom_net()
p + geom_net() + theme_net()
