
tableC
Correlation Table

#### Description

Correlations printed in a nicely formatted table.

#### Usage

<pre><code>
tableC(.data, ..., cor_type = "pearson", na.rm = FALSE, rounding = 3,
output = "text", booktabs = TRUE, caption = NULL, align = NULL,
float = "htb")
</code></pre>

#### Arguments
.data
...
cor_type
na.rm
rounding
output
booktabs
caption
align
float
See Also
stats::cor
the data frame containing the variables
the unquoted variable names to be included in the correlations
the correlation type; default is "pearson", other option is "spearman"
logical (default is FALSE); if set to TRUE, the correlations use the "complete.obs"
methods option from stats::cor()
the value passed to round for the output of both the correlation and p-value;
default is 3
how the table is output; can be "text" for regular console output, "latex2" for
specialized latex output, or any of kable()’s options from knitr (e.g., "latex",
"markdown", "pandoc").
when output != "text"; option is passed to knitr::kable
when output != "text"; option is passed to knitr::kable
when output != "text"; option is passed to knitr::kable
when output == "latex2" it controls the floating parameter (h, t, b, H)14
